export const BuyPage = {
    url: 'https://auto.drom.ru/',
    brand: 'input[aria-controls*="drpdwn"]',
    dropContainer:'[data-ftid="component_select_dropdown"]',
    brCar: 'div[class="css-1r0zrug e1uu17r80"]',
    showBtn: '[data-ftid="sales__filter_submit-button"]',
    pageTitle: 'h1',
    brModel: '[class="css-1r0zrug e1uu17r80"]',
    carDefinition: '[data-ftid="bulls-list_bull"]',
    carTitle: '[data-ftid="bull_title"]',
    cleanBtn: '[data-ga-stats-name="sales_filter_clear_button"]',
    inputModel: '[class="css-mwckxy evnwjo70"]',
    generation: '[data-ftid="component_select_button"]',
    otherCityBtn: '[data-ga-stats-name="geoOverCity"]',
    searchCityField: '[placeholder="поиск города, региона"]',
    cityBtn: '[data-ga-stats-name="geoCity"]',
    location: '[data-ftid="bull_location"]',
    sortBtn: '[data-ftid="component_select_button"]',
    lowPriceLink: 'div[id*=drpdwn]',
    carPrice: '[data-ftid="bull_price"]'
}   